### ISSUE TITLE
Error when trying to install from source

### ISSUE THREAD

**Issue by SeguinBe** [jcrist/skein#12]
I had an issue when trying to install from source during the running of `setup.py`

I had to change [this line](https://github.com/jcrist/skein/blob/73668f449bf37ef498da65cf29b10472d2017498/setup.py#L150) to an empty list instead of `None` otherwise it was creating issue.

Not sure how general my case was though.

**Comment by jcrist** [comment]
Thanks for this issue, this should be fixed in https://github.com/jcrist/skein/commit/3cf5fa64e06f6953754dde03710f70e5ddd678da. I'm not sure why you have this issue and I haven't (perhaps older version of setuptools?), but the fix is fine either way.

**Comment by SeguinBe** [comment]
My version of setuptools is recent though
`setuptools                36.4.0                   py36_1    defaults`

But it was on an edge node machine, so I do not control everything there, despite doing in a user conda environment, so I felt it should have shielded me from weird things.

Thanks for the fix though, managed to start my dask cluster on yarn, did not work with `Knit`. A bit manual for now, (I package the conda env, I run the scheduler on the edge node, then start the workers with skein).

**Comment by jcrist** [comment]
> Thanks for the fix though, managed to start my dask cluster on yarn

That's really good to hear, glad that things worked and the documentation was good enough for you to figure things out. Please file issues if you find any rough edges/lack of docs/etc... Feedback is critical for making this tool nicer to use :).
