### ISSUE TITLE
skein failure on daemon start/stop

### ISSUE THREAD

**Issue by pks2k9** [jcrist/skein#124]
Unable to stop/connect to skein daemon because of Handshake failed with fatal error SSL_ERROR_SSL.

$ skein daemon start
localhost:43586
$ skein daemon stop
```
E1227 01:13:14.561336317   77885 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Error: Unable to connect to daemon
```
$ skein daemon address
```
E1227 01:13:21.258924635   77891 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Error: Unable to connect to daemon
```

**Comment by jcrist** [comment]
> A few things we should do to improve this:
> ...

This has been done in #126, and will be available in the next release.

**Comment by jcrist** [comment]
Closing this, as I believe #126 (and my instructions above) should resolve your inconsistent state. Skein 0.5.0 has been released, and includes this patch. If your issue is not resolved, feel free to reopen.
