### ISSUE TITLE
Run skein in a docker container on edge node

### ISSUE THREAD

**Issue by PierreNowak** [jcrist/skein#129]
Would it be possible to run skein in a docker container on an edge node ?
if yes, do you have some tips on how to do it ?

**Comment by PierreNowak** [comment]
when I use hadoop-testing-kerberos image
mount /etc/krb5.conf, /etc/hadoop and keytab file
set HADOOP_CONF_DIR env var
it seems to be working

**Comment by jcrist** [comment]
Yes, that should work fine. Skein (and most other applications that submits to YARN) needs the following:

- Access to the hadoop configuration files
- Access to the yarn resourcemanager rpc address
- Access to the hdfs namenode rpc address
- Access to the kerberos server address

Anything that provides these is effectively an "edge node" and should work fine.

**Comment by PierreNowak** [comment]
Thank you, 

what about when ssl is enabled on yarn ? I tried mounting java cacerts folder but without success.

**Comment by jcrist** [comment]
I'm not sure, I have no experience with ssl enabled on YARN. If you figure it out please let me know.

**Comment by PierreNowak** [comment]
ok, if you run skein on the edge node with ssl enabled on YARN it simply just works because it uses the java keystore of the edge node.

In my case I was running skein in a docker container with its own java installation. So I had to import the certificates in my java keystore. in htcluster image it looks like:
keytool -noprompt --storepass changeit -import -trustcacerts -alias $ALIAS -file certfiletoimport.crt -keystore $JAVA_HOME/jre/lib/security/cacerts

**Comment by jcrist** [comment]
Ah, good to know. Thanks.

Out of curiousity, why are you running things in a docker container on the edge node?

**Comment by PierreNowak** [comment]
our product is composed of multiple long running services and can be installed on different architectures (local docker, kubernetes, yarn ...). 
one of the service submits computing tasks on the architecture it is running on, it deploys containers on local docker, pods on a kubernetes cluster and applications thanks to skein on a YARN cluster
