### ISSUE TITLE
Compatibility with hadoop3

### ISSUE THREAD

**Issue by fhoering** [jcrist/skein#152]
Currently the Hadoop version is hardcoded to 2.7.2 in 
https://github.com/jcrist/skein/blob/master/java/pom.xml
(it works on our 2.6 Hadoop cluster :))

We will soon migrate to Hadoop3.
I'm wondering if the yarn apis stayed compatible with hadoop3.

**Comment by jcrist** [comment]
Things work mostly the same - I've heard from users using hadoop 3 and things seem to work fine. There are features specific to Hadoop 3 that may be nice to expose (e.g. expanded resource specifications), but I'm not sure the best way to do that in a single codebase.

**Comment by fhoering** [comment]
OK. Thanks. Let's close this for now.
Maybe you can put in the README somehow the supported Hadoop versions.
Once we have a hadoop3 test cluster I will test and create new ticket if necessary. It would be nice to use expanded resource specifications for GPU isolation for example. But let's see once we actually use Hadoop3.

**Comment by jcrist** [comment]
I added Hadoop 3 to our testing infrastructure and can confirm that things work fine. We can add Hadoop 3 specific features later as needed.

**Comment by jcrist** [comment]
Support for Hadoop 3 ``GPU`` and ``FPGA`` resources has been added in the latest release (0.7.1). See https://hadoop.apache.org/docs/r3.1.0/hadoop-yarn/hadoop-yarn-site/UsingGpus.html for gpu-on-yarn documentation.
