### ISSUE TITLE
Document and address Maven dependency.

### ISSUE THREAD

**Issue by simsong** [jcrist/skein#158]
Skein's `build_java` step generates an error if `mvn` is not in the search path:

```
skice-DEV-MASTER:hadoop$ python3 setup.py install
running install
running build_java
creating /mnt/home/hadoop/simsong/skein/skein/java
error: [Errno 2] No such file or directory: 'mvn': 'mvn'
skice-DEV-MASTER:hadoop$ mvn
-bash: mvn: command not found
skice-DEV-MASTER:hadoop$ 
```
If it is going to be required, ideally the script would test for it and give a sensible error if it is not present.

It would also be great of Skein could be installed even if Apache Maven is not present, since Maven is not in the Amazon Linux repo.

**Comment by jcrist** [comment]
Doing a maven install in a `setup.py` script is not something I'd feel comfortable doing - users should take ownership of where non-python tooling lives and having our `setup.py` guess where a user wants to put `maven` is just asking for trouble. The error message when `mvn` is missing could definitely be improved though.

As I mentioned in #157, you don't need to build `skein` local to your machine, you can just `scp` over the wheel and install it locally. It's just a python library with a bundled java jar - nothing is architecture or OS specific.

**Comment by simsong** [comment]
I'm not asking you to do a maven install; I'm asking you to detect if maven is installed or not, and give a reasonable error message if it is not.

**Comment by jcrist** [comment]
The error message has been improved in #160. As far as documentation, please see https://jcrist.github.io/skein/develop.html for instructions on setting up a build environment.
