### ISSUE TITLE
Pass dashboard address to client

### ISSUE THREAD

**Issue by quartox** [jcrist/skein#176]
Our cluster has restricted ports and I found [this page](http://distributed.dask.org/en/latest/web.html#troubleshooting) explaining how to specify the port for the dashboard using the parameter `--dashboard-address`. Is there a way to pass this to the skein client in python?

**Comment by jcrist** [comment]
Apologies for missing this issue. As this is dask-specific issue, I've created a new issue in the dask-yarn repo: https://github.com/dask/dask-yarn/issues/69.

Specifying something like an address is tricky, as we don't know what ports are available on the node. Currently both the scheduler and dashboard ports are chosen as random open ports. Perhaps we should allow configuring a range of viable ports (other tools do this)?

When I use dask-yarn I usually create a new cluster, then port forward the dashboard port as needed.

**Comment by jcrist** [comment]
Moving discussion to https://github.com/dask/dask-yarn/issues/69.
