### ISSUE TITLE
Dask_Yarn Connection issue

### ISSUE THREAD

**Issue by YangYuesong0323** [jcrist/skein#178]
Hi all,

I am trying to use dask_yarn to submit application to yarn. this is the error, i can't figure out why.

Thanks for helping!

mycluster=YarnCluster(environment='compre3.tar.gz')
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/alluxio/client/alluxio-client.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
19/06/24 02:55:39 INFO skein.Driver: Driver started, listening on 36299
E0624 02:55:39.516515079      89 uri_parser.cc:46]           bad uri.scheme: ''
E0624 02:55:39.517023302      89 uri_parser.cc:52]                            ^ here
E0624 02:55:39.517029353      89 http_proxy.cc:58]           cannot parse value of 'http_proxy' env var
19/06/24 02:55:39 INFO skein.Driver: Driver shut down
19/06/24 02:55:40 INFO skein.Driver: Uploading application resources to hdfs://hanameservice/user/yuesongyang/.skein/application_1558958231437_26749
19/06/24 02:55:41 INFO skein.Driver: Submitting application...
19/06/24 02:55:42 INFO impl.YarnClientImpl: Submitted application application_1558958231437_26749
E0624 02:55:49.243283034      89 uri_parser.cc:46]           bad uri.scheme: ''
E0624 02:55:49.243319753      89 uri_parser.cc:52]                            ^ here
E0624 02:55:49.243323570      89 http_proxy.cc:58]           cannot parse value of 'http_proxy' env var
ConnectionError: Unable to connect to application
ConnectionError                           Traceback (most recent call last)
in engine
----> 1 mycluster=YarnCluster(environment='compre3.tar.gz')

/home/cdsw/.local/lib/python3.6/site-packages/dask_yarn/core.py in __init__(self, environment, n_workers, worker_vcores, worker_memory, worker_restarts, worker_env, scheduler_vcores, scheduler_memory, deploy_mode, name, queue, tags, user, skein_client)
    293                                    user=user)
    294 
--> 295         self._start_cluster(spec, skein_client)
    296 
    297     @cached_property

/home/cdsw/.local/lib/python3.6/site-packages/dask_yarn/core.py in _start_cluster(self, spec, skein_client)
    373             app = skein_client.submit_and_connect(spec)
    374             try:
--> 375                 scheduler_address = app.kv.wait('dask.scheduler').decode()
    376                 dashboard_address = app.kv.get('dask.dashboard')
    377                 if dashboard_address is not None:

/home/cdsw/.local/lib/python3.6/site-packages/skein/kv.py in wait(self, key, return_owner)
    653                 return res
    654 
--> 655             event = event_queue.get()
    656 
    657         return event.result if return_owner else event.result.value

/home/cdsw/.local/lib/python3.6/site-packages/skein/kv.py in get(self, block, timeout)
    279         if isinstance(out, Exception):
    280             self._exception = out
--> 281             raise out
    282         return out
    283 

ConnectionError: Unable to connect to application
19/06/24 02:55:55 INFO impl.YarnClientImpl: Killed application application_1558958231437_26749

**Comment by jcrist** [comment]
This just means that your application failed to connect, which is usually due to an application failing to properly start (I should probably make a more informative error for this specific case).

The best way to debug is to look at the application logs:

```
yarn logs -applicationId application_1558958231437_26749
```

**Comment by YangYuesong0323** [comment]
Hi christ, thanks for your explanation.

19/06/24 02:55:39 INFO skein.Driver: Driver shut down

I can't find any log about the reasons why skein drivers are shutting down.

**Comment by jcrist** [comment]
> 19/06/24 02:55:39 INFO skein.Driver: Driver shut down

That's from the driver, and isn't a sign of a problem (nothing logged with `INFO` is a sign of a problem). From the issue before you want the logs from the application, which can be gotten from the `yarn logs -applicationId ...` command.

**Comment by jcrist** [comment]
Closing, as double posted to https://github.com/dask/dask-yarn/issues/76.
