### ISSUE TITLE
Distributing files hosted on http server

### ISSUE THREAD

**Issue by fhoering** [jcrist/skein#191]
When uploading files from an http server it fails with `No FileSystem for scheme: http`
I guess this is normal because hdfs org.apache.hadoop.fs.FileSystem only supports local files and hdfs/viewfs schemas.

Do you think this is something that could be supported by default ? It seems not clear in the [doc](
https://jcrist.github.io/skein/distributing-files.html) at least which schemas are supported.

The fix seems easy to do: detect http scheme and download the file locally. 
In any case not blocking as I can also do it in an adhoc way.

yaml config:
```
files:
      file: http://myserver/file
```

**Comment by jcrist** [comment]
Adding support for additional filesystems is possible as long as it doesn't get out of hand (and the maintenance costs are low). If you were to submit a PR adding support for an http file scheme and it looked reasonably simple enough, I'd be willing to accept it. I have no intentions to work on this personally.

Out of curiosity, what's your use-case here?

**Comment by fhoering** [comment]
OK. thanks for the response.

I finished by adding it to our code base. Indeed this is for some use case which is very specific to our infra. 

https://github.com/criteo/tf-yarn/commit/509da1ec5f12c85d92c7dc71159e8567f6304fa4#diff-ebe3cf5f3a1c3be18b078604dcc052cdR327

We have a scheduler that triggers different jobs with the last release of each package. We use nexus repository manager to host prod pex packages and they are available via a http server. That's why the need to use them from there.
