### ISSUE TITLE
Add ability to pass dynamic environment variables 

### ISSUE THREAD

**Issue by asm0dey** [jcrist/skein#193]
I'm using skein to submit task to yarn from airflow. I need to pass to task several environment variables, which are generated dynamically.

I can't use kv store cause I need this variables to be available at the very start of application.

Currently I'm using skein CLI.

Any iedas on ways to achieve this?

**Comment by jcrist** [comment]
You don't know the environment variables when you submit the application, but you do when you scale a service? You can do this with the `add_container` method (https://jcrist.github.io/skein/api.html#skein.ApplicationClient.add_container) which lets you override environment variables when scaling a service.

**Comment by jcrist** [comment]
If you know them before submitting the application, you can set them in the spec directly https://jcrist.github.io/skein/specification.html#id5

**Comment by asm0dey** [comment]
Flow is following:

I have built Docker container, which contains python application together with skein spec yaml.
This application is de facto venv-packed python application with run script.
This run script needs several environment variables, which are known at time of run (not build!) of docker container and can be passed via envfile (or any other way of passing environment variables to docker)

So I need smth like 

```yaml
env:
  DATE1: "$DATE1"
  DATE2: "$DATE2"
```

where `$DATE1` & `$DATE2` will be read from env where skein is being ran

**Comment by asm0dey** [comment]
Another option is to pass env variables to skein binary itself.

**Comment by asm0dey** [comment]
Hypothetically I can generate skein descriptor on the fly, it's pretty simple, but looks like a dirty hack

**Comment by jcrist** [comment]
We're unlikely to want to support any templating aspects when reading in `yaml` files (there's too many edge cases, and it's not a common use case). I recommend using the Python API for workloads like this. This is commonly done in many other projects using skein, and is fairly straightforward (it's an intended use, and definitely not a "dirty hack"). For example:

```python
import os
import skein

date1 = os.environ["DATE1"]
date2 = os.environ["DATE2"]

spec = skein.ApplicationSpec(
    name="test",
    services={
        "myservice": skein.Service(
            env={"DATE1": date1, "DATE2": date2},
            script='echo "DATE1 is $DATE1, DATE2 is $DATE2"'
        )
    }
)


# **OR** load from a yaml string, and do templating yourself
spec = skein.ApplicationSpec.from_yaml("""
name: test

services:
  myservice:
    env:
      DATE1: {date1}
      DATE2: {date2}
    script: |
      echo "DATE1 is $DATE1, DATE2 is $DATE2"
""")

with skein.Client() as client:
    client.submit(spec)
```

**Comment by asm0dey** [comment]
Thank you for your ideas.

For the record: I think that if skein is kubectl for YARN, we need smth like Helm in this ecosystem true. Possible solution is jinja, I suppose.

Currently I've solved this with templating in shell :)

**Comment by jcrist** [comment]
> if skein is kubectl for YARN

Skein is a simple client library for YARN, and doesn't strive to be any more than that. While it has a CLI, the python API sees the most usage (usually embedded into other projects). Users are welcome to generate specifications any way they see fit, but we're unlikely to add templating to this library itself.

---

Glad you've got things working. Closing, feel free to open a new issue if you run into problems.
