### ISSUE TITLE
can we just use node machine's conda env

### ISSUE THREAD

**Issue by better629** [jcrist/skein#199]
Usually, a application has huge dependent packages. So can we create the env(test_env) in node machine? And to `source activate test_env` to activate the environment in `spec.yaml script`.

I have tried above method, it seems not work. The error is below: 
```
.skein.sh: line 1: activate: No such file or directory
```

- **Version information**

    Please include version information for the following:

    - Python 3.6.9
    - Hadoop version 3.2
    - Skein version 0.8.0

**Comment by jcrist** [comment]
The `activate` script is part of the conda root environment, which (usually) won't be on PATH in a YARN container. I recommend using either

- `/path/to/conda-env/bin/conda run your-command`
- `source /path/to/conda-env/bin/activate your-environment`

But yes, in general as long as a user has read/exec access to files on the node, you can have dependencies already exist on the node just fine.
