### ISSUE TITLE
allocate none gpus but still run

### ISSUE THREAD

**Issue by better629** [jcrist/skein#200]
Hi, Jim
      I installed the hadoop 3.2, and set `gpus: 0` in `spec.yaml`. Then submit the task. 
      But the application can still use the gpu(through nvidia-smi) for that I allocate 0 gpu for the application. Why ?

Thank you!

- **Version information**

    Please include version information for the following:

    - Python version  3.6
    - Hadoop version 3.2
    - Skein version 0.8

**Comment by jcrist** [comment]
Not allocating a GPU in YARN doesn't prevent the user from still using the GPU. The way GPU resources are isolated is just a convention, the user could still access them through other means. This has nothing to do with Skein, it's just how GPU resources work in YARN. See https://hadoop.apache.org/docs/r3.1.0/hadoop-yarn/hadoop-yarn-site/UsingGpus.html for more information.
