### ISSUE TITLE
solution to run skein under supervisor

### ISSUE THREAD

**Issue by better629** [jcrist/skein#202]
In my scene, I use supervisor to manage the server which uses the skein api.
The Hadoop runs in non-root user, but the supervisor runs with root privilege. So when I use the `submit` method, it occurs that `Permission denied: user=root, access=WRITE, inode="/":{username}:supergroup:drwxr-xr-x`. I have tried set `export HADOOP_USER_NAME={username}` in `.bash_profile` but not work.

**Solution:**
    In supervisor `conf.d` folder, you can set the `environment` in your `*.ini` files.  
```
your.ini

add
environment=HADOOP_USER_NAME="{username}"
```
   Then restart the supervisor, it will works.

- **Version information**
    - Python version 3.6
    - Hadoop version 3.2
    - Skein version 0.8.0

**Comment by jcrist** [comment]
Thanks for the information. I'm going to close this as it's not really an issue with skein. When using supervisord to run a process, I recommend setting the `user` field (see http://supervisord.org/configuration.html#program-x-section-values, scroll down a bit, I can't link to the actual docs section). You probably shouldn't run `skein` (or any other server) as the root user.
