### ISSUE TITLE
Skein appears to incorrectly separate multiple instances of a service running on the same node into separate containers.

### ISSUE THREAD

**Issue by atronchi** [jcrist/skein#205]
When scaling a large number of service instances with small resource requirements, yarn may schedule multiple instances on the same physical node. When this happens, each running instance on the same host initializes into the same directory, corresponding to only one yarn container.

I was expecting that each instance would run in a different yarn container, is that not the case?

**Comment by jcrist** [comment]
Multiple instances of a service should result in multiple yarn containers. However, yarn's resource localization will only localize resources once per each physical node (resources are copied to the node, then symlinked into each container's directory), so if you're localizing a directory you may see the same directory even if you have multiple containers (see https://jcrist.github.io/skein/distributing-files.html for more information).

How are you determining that you have only one yarn container per node? Can you provide a reproducible example, or logs from the application (`yarn logs -applicationId <your-application>`)?

**Comment by atronchi** [comment]
I see, sorry for the false alarm! I think each instance was writing configs into the localized directory so they were clobbering each-other when on the same node. Thanks

**Comment by jcrist** [comment]
If you localize `environment.tar.gz` into an `environment` directory, the container's working directory will contain a symbolic link to a single copy of the untar'd `environment.tar.gz`. 

```
/.../container_current_directory/environment -> /.../localization-directory/environment/
```

In a properly configured Hadoop install anything in the localization directory is usually read-only by application code, so I'd be surprised if your application can write there. Either way, I recommend having application code write only inside the container directory, as this will be automatically cleaned up on application termination.
