### ISSUE TITLE
Allocated container with GPU couldn't be accepted by skein

### ISSUE THREAD

**Issue by ei-grad** [jcrist/skein#220]
Containers which require GPUs are rejected by "Safeguard around containers not matching, shouldn't ever be hit" in `ApplicationMaster.handleNewContainer` because of the `resource` object initialization there doesn't take GPU resources in account.

**Comment by ei-grad** [comment]
https://github.com/jcrist/skein/blob/master/java/src/main/java/com/anaconda/skein/ApplicationMaster.java#L1149-L1153

**Comment by ei-grad** [comment]
@jcrist is that safeguard is needed at all? As I see it only raises problems with custom configurations, like AWS EMR or GPUs resources.

**Comment by cguegi** [comment]
I have the same issue when configured 

 WARN skein.ApplicationMaster: container_e54_1603984700251_0035_01_000002 with <memory:1024, vCores:1>, priority 1 doesn't meet requested resource requirements <memory:1024, vCores:1, yarn.io/gpu: 1>, releasing

**Comment by jglaser** [comment]
Here's an example for `dask-yarn`:

```import dask_yarn
import skein
spec = dask_yarn.core._make_specification()
spec.services['dask.worker'].resources = skein.Resources(memory='78G',vcores=1,gpus=1)
cluster = YarnCluster.from_specification(spec)
```

The above is a workaround (hack) for a missing dask-yarn feature (exposing GPU worker resources, which are supported by skein).  It should work with the patch inn #224 applied.
