### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by quasiben** [jcrist/skein#228]
With the inclusion of https://github.com/jcrist/skein/pull/224 a release would be very much appreciated.  The last release was Aug 28, 2019.  If you would like some help here I'd be happy to tag release and make sure conda-forge updates correctly -- I think a bot should pick up the release shortly after tagging

**Comment by jcrist** [comment]
Version 0.8.1 has been released (only 1 commit of code change since 0.8.0, didn't feel like a major release). On PyPI now, should be on conda-forge shortly.

**Comment by quasiben** [comment]
Thanks @jcrist !
