### ISSUE TITLE
Release 0.8.2 - an issue with clear steps for minimal maintenance effort

### ISSUE THREAD

**Issue by consideRatio** [jcrist/skein#245]
@jcrist sorry to bug you, but I'd really love your help to get the following PRs merged as `skein` is a dependency for dask-gateway. If possible, also accompanied with a 0.8.2 release including these small changes. With that, I can overcome https://github.com/dask/dask-gateway/issues/401 and other issues like dropping support for Python 3.7 without breaking the CI system the Yarn backend etc.

## Action points I'd like your help with

- [ ] #241
- [ ] #242 
- [ ] #243 (just some inline docs for a person like me that ends up debugging something)
- [ ] #244
- [ ] Cut a release
  This should be what you need to do I think.

  ```shell
  # after merged PRs, ensure you are up to date
  # in your local git repo
  git pull
  git log
  
  # cleanup possible old artifacts
  git clean -xfd
  git status
  
  # setup an environment to build a release
  conda create -y -n skein
  conda activate skein
  conda install -y -c conda-forge grpcio protobuf cryptography pyyaml maven
  pip install "grpcio-tools!=1.45"
  
  # create a tag for versioneer
  git tag -a 0.8.2 -m "Version 0.8.2"
  python setup.py install
  
  # verify the .jar and proto files got generated
  ls -alh skein/java
  ls -alh skein/proto
  
  # install tools to produce a sdist/wheel and upload them to PyPI
  pip install build twine
  
  # produce sdist/wheel and inspect result
  build --sdist --wheel .
  ls -alh dist/
  
  # upload to PyPI
  twine upload --skip-existing dist/*
  ```

**Comment by jcrist** [comment]
Thanks Erik, 0.8.2 has been released to pypi, will be on conda-forge once the bots find it.

**Comment by consideRatio** [comment]
Wieee thank you Jim :heart: :tada:!!
