### ISSUE TITLE
Start daemon/init automatically?

### ISSUE THREAD

**Issue by mrocklin** [jcrist/skein#25]
I can see arguments both ways on this, but I thought I'd bring it up for discussion explicitly.

```
[testuser@edge skein]$ skein application submit hello.yaml 
Error: Skein daemon not found, please run `skein daemon start`
[testuser@edge skein]$ skein daemon start
Error: Skein global configuration directory is not initialized. Please run ``skein init``.
[testuser@edge skein]$ skein init
```

The error messages here were clear and pointed me to correct action, but it might be worth automating these, possibly with a verbose message.

**Comment by jcrist** [comment]
Automatic init was added in #27 (with a nice warning). I'm not sure if I want to automatically start the daemon yet, will have to think.
