### ISSUE TITLE
Atomic counters

### ISSUE THREAD

**Issue by superbobry** [jcrist/skein#33]
I'm still looking for a good way to synchronize multiple containers. The between-service dependencies solve the startup issue, but I'd also like to sync before shutting down the container. The simplest way to do this is to have a counter which goes from the number of containers to zero. However, this requires atomic decrements. Do you think it is possible to support them in skein?

**Comment by jcrist** [comment]
This would definitely be doable and be in scope. That said, I'm trying to keep the internals of skein as simple as possible, only providing enough primitives that things work. Can you elaborate more on your use case?

**Comment by superbobry** [comment]
My goal is to distribute TensorFlow training on YARN using skein. I'm 90% there, but I'd like to make some of the components cleaner. One of the components is a double-barrier which is needed to synchronize all the containers before starting the training, and directly after it. 

I've implemented the "start" barrier using dependencies between services. Now, I'd like to implement the "done" barrier via the KV store. All I need is a counter which can be modified by the containers in a race-free way. Once the container is done with the training, it will do a -1 and will then poll the counter until it reaches 0 (could also be the other way round -- +1 and n_containers). Once the counter is 0, all the containers are done, and the job can exit.

**Comment by jcrist** [comment]
The key-value store was documented in #49, and is available here: https://jcrist.github.io/skein/key-value-store.html (hopefully it's useful).
