### ISSUE TITLE
Block until application has finished

### ISSUE THREAD

**Issue by superbobry** [jcrist/skein#46]
This is probably something every user of `skein` needs: submit an app and wait until it's done, logging relevant debugging information (e.g. container log URLs) in case of failure.

IIUC currently it is impossible to reliably get the final application status w/o a race condition with the daemon shutdown.

**Comment by jcrist** [comment]
> This is probably something every user of skein needs: submit an app and wait until it's done, logging relevant debugging information (e.g. container log URLs) in case of failure.

Can you expand on your use case here? I see 2 ways of using skein:

- Write a specification that is self contained, and use either the cli or python api to submit the application to run later without any coinciding process on the edge node. E.g. `skein application submit test.yaml` runs the application on the cluster, nothing more is needed. I expect this use case to be uncommon.

- Use the python api to build a larger integration with some other library (e.g. dask). This was my use case. A user then has a small process running on the edge node, and the lifetime of the yarn application is tied to the lifetime of this process. I expect this case to be more common.

> IIUC currently it is impossible to reliably get the final application status w/o a race condition with the daemon shutdown.

I'm not sure what mean by this. Can you expand?

Taking a guess: YARN assumes the user has their own communication setup to manage things like determining when the application has started/finished/failed. For my case (dask) this happens to be true (I can determine independent of skein when my dask cluster has started/shutdown). In the case that it's not, you'd either need to startup some small network (even just a socket to wait on locally, and have your application write to it when done), have skein also track application shutdown (I'd rather not, but could), or poll the application status until completed (shouldn't be too bad). Something like:

```python
while True:
   report = client.application_report(app_id)
   if report.final_status != 'undefined':
      break  # succeeded/failed/killed
   time.sleep(1)
```

**Comment by superbobry** [comment]
Thank you for an extended reply. I have implemented a variant of the while True loop with container<->edge node communication via the K/V store.

**Comment by jcrist** [comment]
Nice. Is this code public anywhere? Seeing how others use things would be informative.

**Comment by superbobry** [comment]
It isn't yet public, but we plan on open-sourcing it in the coming months.
