### ISSUE TITLE
Recommended python HDFS package

### ISSUE THREAD

**Issue by PierreNowak** [jcrist/skein#59]
Do you have any recommended python packages to execute HDFS commands in a container launched by skein?

It seems there is only a token file in containers located at HADOOP_TOKEN_FILE_LOCATION.
hdfs dfs cli works fine.
pyarrow seems to be preferred to hdfs3 but it doesn't handle delegation tokens.

Thanks

**Comment by jcrist** [comment]
Are you sure `pyarrow.hdfs` doesn't handle delegation tokens? I just tried on a kerberized cluster and everything worked fine.

```python
import pyarrow.hdfs as hdfs
fs = hdfs.connect()
fs.ls("/")
```

The java hdfs library loads delegation tokens found at `HADOOP_TOKEN_FILE_LOCATION` automatically, and `libhdfs` is a jni wrapper around the Java lib, so I'm not sure why this wouldn't be supported.

**Comment by PierreNowak** [comment]
indeed ... 

totally misunderstood this one : https://issues.apache.org/jira/browse/ARROW-1321

Thanks !
