### ISSUE TITLE
Barrier implementation options

### ISSUE THREAD

**Issue by superbobry** [jcrist/skein#6]
I am looking into implementing a barrier on top of keystore for synchronizing multiple services. One way to do it would be for each service to create an "init/<ID>" key, and block waiting for a GO from the app master. The app master, on the other hand, could wait for all the init keys, and issue a GO when all of them are there. 

Does this sound like something the keystore could handle?

**Comment by jcrist** [comment]
Keep in mind that I wouldn't say this library is still in beta and not "ready for use" yet (I've added a note clarifying this). That said, this should be doable using the keystore. I'd handle this by having each service start up, set its corresponding key, then issue subsequent blocking waits for each other service. Does that make sense?

**Comment by jcrist** [comment]
Closing for now as I believe this question has been answered. Feel free to reopen/open a new issue if you have other questions. Note that the "still in beta" remark above no longer holds, I'd say this library is usable at this point :).
