### ISSUE TITLE
Document different strategies for distributing python environments/libraries

### ISSUE THREAD

**Issue by jcrist** [jcrist/skein#62]
As an alternative to using `conda-pack`, we should also document how to bundle up an application using other strategies. A few potential options:

- [x] package a virtual environment
~- [ ] PEX (added from below)~

~*edit: I no longer think a wheel is the best method, switched to using virtual environments for non-conda, and also want to try out PEX*~

**Comment by superbobry** [comment]
[PEX](https://pex.readthedocs.io/en/stable/) might also be an option.

**Comment by jcrist** [comment]
Interesting, hadn't heard of that one before. I also just wrote up a solution that works with `venv`/`virtualenv`: https://jcrist.github.io/venv-pack/.

**Comment by jcrist** [comment]
Hmmm, so I've evaluated PEX and am not sure I'd recommend it for use on YARN over other options.

PROS:
- Can package an application on one architecture/OS and deploy it on another. This can be useful if developing on osx but deploying on linux cluster.
- Only need one command in the `commands` list (no need to `source environment/bin/activate`). I don't see this as that big of a benefit, adding commands to a service isn't a big impediment.

CONS:
- The YARN resource localization process caches files locally per-node. If the file is marked as an archive, it's decompression is also cached, and the directory is symlinked into the container directory. This plays very well with tools like [conda-pack](https://conda.github.io/conda-pack/) and [venv-pack](https://jcrist.github.io/venv-pack/) which only require decompressing the archive.

  In contrast, `pex` files unpack the archive into a private cache directory if any of the dependencies aren't zip-safe (which is common, if unnecessary). By default this is `~/.pex`, but can be specified at creation. To use pex on yarn you'd often need to change this (perhaps `.pex` or `/tmp/pex`), as the default directory usually won't be writable. This cache mechanism is external to YARN's, and adds another set of things to worry about.

- Startup time is a lot slower, even if starting on the same node. This is because the zip archive still needs to be opened and the cache directory inspected.

- Has the same downsides as `venv-pack` (python must be present on the system, as well as non-python dependencies).

**Comment by jcrist** [comment]
Closing for now. I'm happy with both a conda and non-conda solution. Other packaging/distribution methods can be discussed in new issues.
