### ISSUE TITLE
Initiate Spark like engine

### ISSUE THREAD

**Issue by hamroune** [jcrist/skein#75]
The idea is to write the functional Dataframe let say a SkeinDataFrame with same spark API

sdf.read.parquet("path/to/parquet")
sdf.map(anyMapFunc)
sdf.filter(anyBooleanFilterFunc)
sdf.groupBy("colA", "colB")
sdf.reduce
etc...
what do you think about that?

**Comment by hamroune** [comment]
I just find a wonderful project http://dask.pydata.org/en/latest/dataframe-api.html

**Comment by jcrist** [comment]
Running Dask on YARN was the original motivator for writing Skein. See https://github.com/dask/dask-yarn.

**Comment by jcrist** [comment]
The error message suggests how to solve your problem (increase the number of bytes being read as a sample). You also might first try debugging things locally without a distributed scheduler (dask works fine on a single machine like a laptop).

```python
>>> import dask.dataframe as dd
# Try increasing the sample size
>>> dd.read_csv('gs://my-bucket/sample.csv', sample=512000).head()
# or try debugging locally
>>> dd.read_csv('sample.csv').head()
```
