### ISSUE TITLE
Human-readable memory strings in skein.Resources

### ISSUE THREAD

**Issue by superbobry** [jcrist/skein#86]
What do you think about changing the constructor of `skein.Resources` to accept memory as either a number of megabytes, or a string, e.g. "5G" or "1024M"? This could be a bit more readable for bigger containers. We routinely allocate 20-30G, and 20 * 2**10 does not look as nice.

**Comment by jcrist** [comment]
I'd be fine with that. Dask-Yarn already supports this, would be happy to port it over. See https://github.com/dask/dask/blob/master/dask/utils.py#L950-L1016

**Comment by jcrist** [comment]
This is added in #87. Note that the default unit is `MiB` (1024 MiB in a GiB) not `MB` (1000 MB in a GB). See [here](https://en.wikipedia.org/wiki/Mebibyte) for more information. This is a carryover from YARN, which mistakenly labels its units as MB, but really means MiB.

Memory parameters are normalized on input to integer units of mebibytes, with the following rules:

- If no unit or numeric, it's interpreted as in MiB already (matching the current behavior, and YARN).
- Units are case normalized (`GB == gb`), and the `B` is unnecessary (`G == GB`, `Gi == GiB`)
- Requests that are smaller than 1 MiB are rounded up to 1 MiB.
- Requests that aren't an even number of MiB are rounded *up* to the nearest MiB.
