### ISSUE TITLE
Ability to set allowed hostnames for a service 

### ISSUE THREAD

**Issue by sauercrowd** [jcrist/skein#89]
I'm not sure if that would be possible, but it would be really handy if when creating a service it is possible to pass a list of allowed hosts, from where the service picks as many nodes as required.

Reason: it would make it possible to set specific hosts even without node labels, which is helpful for deployments where you are not allowed to change the cluster configuration but still have to rely on specific nodes for specific services.

What do you think about that?

**Comment by jcrist** [comment]
Thanks for the issue report. This was pretty easy to add - it's another part of a YARN container request that we previously didn't expose :). Should be fixed in #90.

**Comment by sauercrowd** [comment]
That's awesome! Thanks!
